### ISSUE TITLE
test_net_speed/test_mnist throwing SIGTRAP

### ISSUE THREAD

**Issue by ZenginU** [tinygrad/tinygrad#1355]
With #1335, running test_net_speed/test_mnist throws SIGTRAP on METAL. Not throwing every time but most of the time. 

Test do not fail even with the SIGTRAP but Python quit unexpectedly shows up.

**Comment by zboralski** [comment]
I can see a trap in `test/test_net_speed.py` as well.

The SIGTRAP we're encountering might be due to a "use after free". The `__del__` method is invoked when an object is about to be destroyed, and this can occur at unpredictable times. If GPU commands that use the buffer are still being dispatched after the buffer is released, this could result in a "use after free" error.

If we add a synchronization call within the `__del__` method of the `RawMetalBuffer`. This ensures that all GPU commands finish executing before the buffer is released. 

```python
class RawMetalBuffer(RawBufferMapped):
  def __init__(self, size:int, dtype:DType):
    super().__init__(size, dtype, METAL.device.newBufferWithLength_options_(size*dtype.itemsize, Metal.MTLResourceStorageModeShared))
  def __del__(self):
    METAL.synchronize()  # Ensure all GPU commands finish before releasing the buffer
    self._buf.release()
    super().__del__()
  def _buffer(self):
    METAL.synchronize()
    return self._buf.contents().as_buffer(self._buf.length())
```

**Comment by wozeparrot** [comment]
#1335 has been reverted.
