### ISSUE TITLE
openpilot elementwise fusion broke (fixed / not merged)

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#1781]
b12b60af2063ff148f0bde8cee8985bd0cf39cf5 broke it somehow

Can you get the `v0.9.4` openpilot model to compile with 207 kernels down from 209? Run `openpilot/go.sh`

Kernels 69 and 120 should be fused with 68 and 119 respectively.

**Comment by WarPromo** [comment]
I will give 1 dollar on top of that to whoever fixes it.

**Comment by sahamrit** [comment]
logic behind why only certain movement ops are allowed for "replace_with_movement_ops" ?
```
  def _movement_op(self, st: ShapeTracker, op: MovementOps, arg: Union[Tuple[sint, ...], Tuple[Tuple[sint, sint], ...]]) -> LazyBuffer:
    if SHUFFLE_MOVEMENT_OPS and self.optype == BinaryOps and not self.realized and (op in {MovementOps.SHRINK, MovementOps.STRIDE, MovementOps.PERMUTE} or (op == MovementOps.RESHAPE and self.op.op in UnaryOps)) and not self.children:
      return self.op.replace_with_movement_ops([(op, arg)])
```

I was analysing this [MR](https://github.com/tinygrad/tinygrad/pull/1789) & found the exact reason as to why "allowing reshape being pushed up through BinaryOps got the kernel count back from 209 -> 207" [link to my comment](https://github.com/tinygrad/tinygrad/pull/1789#issuecomment-1747384954).

I need clarity on what basis are certain Movement Ops allowed through certain BinaryOps.

**Comment by sahamrit** [comment]
@geohot as per my above comment, if the kernel count is to be reduced from 209 -> 207, reshape needs to be pushed up through BinaryOps which was disabled in [this commit - push reshape through UnaryOps](https://github.com/tinygrad/tinygrad/pull/723/commits/11732cae4af4b23e31b2fe99d1f4c90067bda7ee)

I assume you restricted reshape through UnaryOps, so that `test_no_binop_rerun` passes ? However tests like these will fail for permute, prereshape etc. So a better way of ensuring these test passes is needed instead of restricting "reshape through Unary only"?

lmk if my understanding is sound!

**Comment by sahamrit** [comment]
Can we have a bounty lock on this issue?

**Comment by sahamrit** [comment]
@wozeparrot can close this issue. Done with PR #2006.
However the PR was reverted due to an outstanding unrelated CI issue #2065. So not sure.

**Comment by wozeparrot** [comment]
Gonna leave this open until the fix is actually merged.
