### ISSUE TITLE
max(symbolic, int) has unexpected behaviour

### ISSUE THREAD

**Issue by gijskoning** [tinygrad/tinygrad#1924]
The following fails:
```
vi = Variable("i", 1, 10)
assert max(5, vi) == max(vi, 5)    
```
Because  `max(5, vi) == <i[1-10]>`
And `max(vi, 5) == 5`

Sorry I don't have a fix for it at the moment but do want do mention it.

And it looks like we use max on symbolic: https://github.com/tinygrad/tinygrad/blob/9c6bb7ff1344c198de21b23290bc576b3a8c9219/tinygrad/codegen/optimizer.py#L243

**Comment by geohot** [comment]
Hmm cool find.

**Comment by gijskoning** [comment]
I couldn't get my head around it either. It depends a bit on the use case, but I think most of the time you want the real maximum number. You could have Node.max(nodes) which retrieves the real max number for every node and then returns the maximum of all.

**Comment by ronak69** [comment]
`max()` compares its arguments to determine the largest one. That results in `LtNode`s being used in `if` statements (which in turn get converted to `bool`).

```python
x = Variable("x", 1, 10)
assert bool(x < 5) == True
assert bool(x > 5) == True
```

`x < 5` is an instance of `LtNode` which will always get converted to `True` regardless of whether `x` will be less than `5` or not.

---

`max(5, vi)` is equal to `vi` because `vi > 5` is `True`.
`max(vi, 5)` is equal to `5` because `5 > vi` is also `True`.
