### ISSUE TITLE
pad on METAL backend has issue with inf/-inf/nan as fill value

### ISSUE THREAD

**Issue by geohotstan** [tinygrad/tinygrad#2067]
reproduce:
```
Device.DEFAULT = "METAL"
a = Tensor.rand(16,16).pad(tuple([(2, 2), (2, 2)]), value=float("inf"))
print(a.numpy())
```
There are 0's in places where there shouldn't.
I've only tried limited examples but with rand with a shape large enough, 0's starts to appear.

**Comment by g-cassie** [comment]
I was trying to get familiar with the repo/ml/metal and used this issue as a jumping off point. I wonder if this may be due to the `fastMathEnabled` flag being on by default in Metal.  Relevant docs:

![Screenshot 2023-10-16 at 3 09 16 PM](https://github.com/tinygrad/tinygrad/assets/4053345/0d427344-027c-4a65-b271-53ef06e77f50)
![Screenshot 2023-10-16 at 3 20 05 PM](https://github.com/tinygrad/tinygrad/assets/4053345/e2532abf-7fcd-43db-ab30-fccfa9176df6)

That said, when I add `options.setFastMathEnabled_(0)` in `ops_metal.py` it does not seem to solve the problem. 

I found `rand(8192, 8192)`reliably produces a few zeros on my macbook air.

In case it's not obvious, I am very out of my depth!

**Comment by geohotstan** [comment]
I'm also **_very_** out of my depth too haha
I'll play around with disabling fastmath

But yeah I think tinygrad has fastmath enabled on every runtime that supports fastmath
fastmath also causes some inaccuracy on some other places too like #1791

I wonder if it'd be ok to enable fastmath using an OPT flag when we gotta go fast
but optionally turn it off for more accuracy and correctness. 🤔

**Comment by gabelerner** [comment]
isn't rand declared here: https://github.com/tinygrad/tinygrad/blob/master/tinygrad/realize.py#L71
which does this https://github.com/tinygrad/tinygrad/blob/master/tinygrad/realize.py#L43-L44
and then `rng = np.random.default_rng(); a = rng.random(size=8192*8192, dtype=np.float32); np.where(a == 0)` causes 0's to happen because np implements it with https://github.com/numpy/numpy/blob/main/numpy/random/src/distributions/distributions.c#L20 which is essentially 24 bits and when you do `8192*8192/2^24` you get 4 meaning on average you'll have 4 0's in the array.

similarly `a = Tensor.rand(8192,8192).pad(tuple([(2, 2), (2, 2)]), value=float("inf")); b = a.numpy(); np.where(b == 0)` gives 4 0's on average (the pad doesn't matter, can just be `a = Tensor.rand(8192,8192); b = a.numpy(); np.where(b == 0)` and you still get 0's)

**Comment by g-cassie** [comment]
Makes sense - and I think I was probably seeing an average of four zeros when I was trying to replicate this.

Any other detail on the original bug that gave rise to this issue?

**Comment by geohotstan** [comment]
> Makes sense - and I think I was probably seeing an average of four zeros when I was trying to replicate this.
> 
> Any other detail on the original bug that gave rise to this issue?

`tinygrad/test/external/external_test_onnx_backend.py 164:167` 
```
# issue 2067 potentially also a fastmath issue https://github.com/tinygrad/tinygrad/issues/2067
if getenv('METAL'):
  backend_test.exclude('test_maxpool_2d_pads_cpu')
  backend_test.exclude('test_maxpool_2d_same_lower_cpu')
```

**Comment by g-cassie** [comment]
Those two tests pass on my M2. I ran them 10 times each to see if they were flakey. Also tried them both on master and on the commit where you added them.  

These ones all fail though:
```
# issue 1791 fast math messes with these https://github.com/tinygrad/tinygrad/issues/1791
if getenv('METAL') or getenv('LLVM'):
  backend_test.exclude('test_resize_upsample_sizes_nearest_axes_2_3_cpu')
  backend_test.exclude('test_resize_upsample_sizes_nearest_axes_3_2_cpu')
  backend_test.exclude('test_resize_upsample_sizes_nearest_cpu')

...

if getenv('GPU') or getenv('METAL'):
  backend_test.exclude('test_mish_cpu') # weird inaccuracy
  backend_test.exclude('test_mish_expanded_cpu') # weird inaccuracy
  backend_test.exclude('test_eyelike_with_dtype_cpu') # backend does not support dtype: Double
```

Would it be worth it for me a PR removing the exclusions for the maxpool tests?

**Comment by geohotstan** [comment]
> Those two tests pass on my M2. I ran them 10 times each to see if they were flakey. Also tried them both on master and on the commit where you added them.

oh that's so weird... 
on master for me when I run the test (I have a m1 pro)
```
METAL=1 pytest test/external/external_test_onnx_backend.py
...
FAILED test/external/external_test_onnx_backend.py::OnnxBackendNodeModelTest::test_maxpool_2d_pads_cpu - AssertionError: 
FAILED test/external/external_test_onnx_backend.py::OnnxBackendNodeModelTest::test_maxpool_2d_same_lower_cpu - AssertionError: 
==================================================================== 2 failed, 908 passed, 1724 skipped, 1 warning in 19.31s =====================================================================
```

> Would it be worth it for me a PR removing the exclusions for the maxpool tests?

If it passes for CI, then yeah I guess the exclusions can be removed in a PR,
though the reproduce case is still giving 0's

**Comment by g-cassie** [comment]
The reproduce case you posted initially didn't give 0s on m2 until I put the dimensions very high. @gabelerner is likely correct that I was just getting an average number of zeros based on how many random numbers I was generating.

I'll try to mess with the other tests that do fail on the M2 and see whether I can figure anything out.

**Comment by g-cassie** [comment]
Just occurred to me it could also be different versions of the SDK.

Here's mine
```
>>> xcrun -sdk macosx metallib --version   
Apple metal version 31001.720 (metalfe-31001.720.3)
```

**Comment by geohotstan** [comment]
> I wonder if it'd be ok to enable fastmath using an OPT flag when we gotta go fast
> but optionally turn it off for more accuracy and correctness. 🤔

#3369 added a env var (I called it an OPT flag...) for fastmath so I consider this issue fixed :D
