### ISSUE TITLE
Have a passable (vaguely mistakable for human) voice conversation with tinygrad (whisper + LLaMA + VITS)

### ISSUE THREAD

**Issue by shauray8** [tinygrad/tinygrad#2249]
I do not see anyone working on [this](https://docs.google.com/spreadsheets/d/1WKHbT-7KOgjEawq5h5Ic1qUWzpfAzuD_J06N1JwOCGs/edit#gid=0&range=A50), do you have any specifics in mind for this on how this should be done? or any tests?
@wozeparrot @geohot 

---

Current Bounty: $400
To lock the bounty submit a draft PR with a decent amount of progress made
Make sure to reference this issue in the PR for future tracking

Notice: _If the PR goes stale the bounty will be unlocked_

**Comment by wpmed92** [comment]
For any bounty a first step is to put up a good draft pr, if it's good enough the bounty will be locked for your.

**Comment by geohotstan** [comment]
dosier did an attempt at this before #1396 
check it out since he has done a lot of the API work already
I'm pretty sure he's got a good idea on how it should be done (he claimed the VITS TTS bounty)

I remember geohot mentioning in discord that the conversation has to stream like a natural convo
so basically create a demo that is capable of streaming the convo with low enough latency

**Comment by wozeparrot** [comment]
Going to use this as the tracking issue.

**Comment by J4e6eR** [comment]
@geohotstan @wozeparrot How to join the discord server, I found the invite link from the tinygrad website but that doesn't seem to work for me. 
I don't know why I am getting this error, is there any alternative way to join ?? 
I've been trying to join since a month.
![image](https://github.com/tinygrad/tinygrad/assets/91129126/f007e935-0242-438a-bb67-22a2e983aa7f)

**Comment by J4e6eR** [comment]
@geohotstan @wozeparrot I am sorry, to divert off from the main topic but helping me out in joining tinygrad's official discord server would truly be appreciable. I'll delete these comments after that for sure!!

**Comment by wozeparrot** [comment]
> @geohotstan @wozeparrot I am sorry, to divert off from the main topic but helping me out in joining tinygrad's official discord server would truly be appreciable. I'll delete these comments after that for sure!!

Can you move this to a discussion? thanks

**Comment by J4e6eR** [comment]
> @J4e6eR Can you move this to a discussion? This really isn't the place for stuff like this.
Added in the discussions tab, please have a look 
https://github.com/tinygrad/tinygrad/discussions/2276

**Comment by MeDott29** [comment]
Sweep: figure out how to solve this issue

**Comment by chenyuxyz** [comment]
done #2332
