### ISSUE TITLE
`Tensor.cat` is extremely slow on CPU

### ISSUE THREAD

**Issue by blueridanus** [tinygrad/tinygrad#2526]
You can also reproduce by just checking how long `load_state_dict` takes on the CPU, making e.g. `llama.py` take forever to load.

```python
from tinygrad import Tensor
from tinygrad.helpers import Timing

print("CPU:")
for i in range(20):
    a = Tensor.randn(10**8).to('cpu').realize()
    b = Tensor.randn(10**8).to('cpu').realize()

    with Timing():
        a.cat(b).realize()

print("\nGPU:")
for i in range(20):
    a = Tensor.randn(10**8).to('gpu').realize()
    b = Tensor.randn(10**8).to('gpu').realize()

    with Timing():
        a.cat(b).realize()
```

```
CPU:
219.86 ms
220.34 ms
219.89 ms
220.38 ms
220.74 ms
224.31 ms
221.89 ms
222.05 ms
222.70 ms
221.25 ms
221.56 ms
224.61 ms
219.80 ms
223.94 ms
221.83 ms
218.34 ms
222.32 ms
222.02 ms
218.96 ms
222.69 ms

GPU:
75.17 ms
0.25 ms
0.26 ms
0.26 ms
0.26 ms
0.25 ms
0.25 ms
0.25 ms
0.25 ms
0.26 ms
0.25 ms
0.25 ms
0.25 ms
0.25 ms
0.26 ms
0.25 ms
0.25 ms
0.26 ms
0.25 ms
0.25 ms
```

**Comment by blueridanus** [comment]
Current impl does PAD + ADD. Does this require a new movement op?

**Comment by blueridanus** [comment]
`CLANG=1` is even worse at ~500ms

**Comment by chenyuxyz** [comment]
it's better to run the same script with different backend flag than using `to`, otherwise we are including the copy time between devices.

also CPU is blocking and GPU is not, so you need to add a numpy() or wait, or the 0.25ms is just python finishing sending instructions to GPU

compiled backed takes time to compile too, so to measure the kernel speed, you can jit the function (e.g. this speed test script https://github.com/tinygrad/tinygrad/blob/master/test/test_speed_v_torch.py)
