### ISSUE TITLE
ModuleNotFoundError: No module named 'extra'

### ISSUE THREAD

**Issue by m000lie** [tinygrad/tinygrad#2550]
i can't run examples/efficientnet.py so i decided to create a new `__init__.py` file in extra/. But when i run that newly created `__init.py__` file with a single statement inside `from extra import *`, i get slapped with a MNFE. Why can't python detect `extra`?

**Comment by wozeparrot** [comment]
You can try with `PYTHONPATH=. python examples/efficientnet.py`

**Comment by m000lie** [comment]
should i put that line in examples/efficientnet.py file?

**Comment by m000lie** [comment]
awesome! thank you @wozeparrot !

**Comment by beverm2391** [comment]
Update, having the same issue. 

I did dome diagnostics and realized that when python imports **extra** from within the `/test` directory, it actually imports from the 'tinygrad/test/extra' dir instead of the 'tinygrad/extra' dir. I believe this is called _shadowing_.

My sys.path includes my venv site-packages and the absolute path to the tinygrad root, as normal.

I have yet to find a fix that avoids refactoring the import statements to be absolute or changing the name of one of the modules. Happy to draft a PR if this is deemed important.

**Comment by beverm2391** [comment]
Update. The CI/CD tests were passing and I realized that running `pytest {file.py}` passes while just executing the file `python {file.py}` doesn't, for whatever reason. Documenting this here for the next person.
