### ISSUE TITLE
Export safetensors as ONNX/Pytorch/Tensorflow model

### ISSUE THREAD

**Issue by michbogos** [tinygrad/tinygrad#3307]
I'm looking for a way to convert a trained model to an ONNX model to use on the web. I've only found how to run ONNX models in tinygrad, but not how to export them.

An nice addition would also be to export to a pytorch or a tensorflow model to use on embedded devices and on the web.

**Comment by terafo** [comment]
There's no way to export tinygrad model to onnx, torch/torchscript or tensorflow/tflite and it's not in scope of a project at a time. There is, though, webgpu backend that was removed last month in order to focus on, but it still should work(extra/backends/ops_wgpu.py), or at least easy to fix and there is a way to export webgpu model so it can run on web(extra/export_model.py). If you absolutely need to run tinygrad model on web you might want to consider this path, but there are dragons there.

**Comment by michbogos** [comment]
Thanks for the information.

**Comment by chenyuxyz** [comment]
close as not planned

**Comment by roman-koshchei** [comment]
That's very sad
