### ISSUE TITLE
error casting between dtypes.double and dtypes.half on CLANG

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#4084]
probably target dependent, `__fp16` is for ARM only? but CI passes too

example, with `CLANG=1`
```
a = Tensor([1, 2, 3], dtype=dtypes.double)
print(a.numpy())
print(a.cast(dtypes.half).numpy())
```

source
```
#include <stdbool.h>
#include <tgmath.h>
#define max(x,y) ((x>y)?x:y)
#define half __fp16
void E_3(half* restrict data0, const double* restrict data1) {
  for (int ridx0 = 0; ridx0 < 3; ridx0++) {
    double val0 = data1[ridx0];
    data0[ridx0] = (half)(val0);
  }
}
```

on mac m1 max
```
[1. 2. 3.]
[1. 2. 3.]
```

on tinybox, ubuntu 22.04
```
[1. 2. 3.]
[0.00e+00 0.00e+00 3.05e-05]
```

**Comment by mooihi** [comment]
Do we need __fp16 since we are not passing the appropriate flag to utilise it properly even for ARM processors?
The new runners do not have gcc-13 installed, this is inline with Ubuntu 22.04 default gcc package versions (up to gcc-12). The old runner had gcc-13 installed and clang seemed to be able to use those header files and compile the library properly.
Changing __fp16 to _Float16 passes the CI, this is the recommended type anyway.
[https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html](url)

**Comment by chenyuxyz** [comment]
fixed in https://github.com/tinygrad/tinygrad/pull/8265
