### ISSUE TITLE
Bump mypy to 1.12.1

### ISSUE THREAD

**Issue by geohot** [tinygrad/tinygrad#7176]
And fix the type issues

**Comment by Sean-fn** [comment]
Hello @geohot , I'm working on this, can you assign this to me?

While I checked the [latest version](https://github.com/python/mypy/releases/tag/v1.13.0) of `mypy` , it is now 1.13.0 , should we go for it?

**Comment by mku11** [comment]
Regarding: #7381. As I said in the PR I'm afraid there is no other way, it is mypy that expects: def cast(self, *args, **kwargs). Controversy is part of developement and it is followed by someone that make a decision. Also as I said the other way is to simply type: ignore it until someone comes with a godly solution that I don't have. So can someone make a decision on this?

**Comment by mku11** [comment]
Just to make it simpler these are the options I see:
1. Cast params to Any and close the issue. As I also said this I don't like it though it's an option.
2. type: ignore and close the issue. The cast type problem becomes a new issue until someone comes up with a solution or it is supported by mypy.
3. Keep this Issue open because of one subitem.

**Comment by kayo09** [comment]
@Sean-fn did you start working on this, are you using my 1.13.0 or 1.12.1?
