### ISSUE TITLE
TRANSCENDENTAL=2 Tensor([11], dtype='half').exp() returns inf

### ISSUE THREAD

**Issue by chenyuxyz** [tinygrad/tinygrad#7421]
TRANSCENDENTAL=2 METAL=1 python -c "from tinygrad import Tensor; print(Tensor([11], dtype='half').exp().float().item())"

same inf for METAL/AMD/NV. CLANG and LLVM gives the correct ~59770.

**Comment by eliotgolding** [comment]
This is caused by the order of multiplys in ldexp2k, the python has `(d*pow2if())*pow2if()` but the generated kernel does `pow2if()*pow2if()*d`. So when the input is large the first part of the multiply goes to inf. A fix is to add two bitcasts to force the order of multiplys in the generated code, it's zero cost because it's a bitcast but it's a bit of a hack.

CLANG only gives the correct answer because of its casting behaviour when casting __fp16 to float, try e.g. `CLANG=1 python -c "from tinygrad import Tensor; print(Tensor([30000], dtype='half').mul(200).float().item())"` which doesn't give inf despite being bigger than max fp16.

**Comment by chenyuxyz** [comment]
yea that fix is not good enough, we just don't have a rewrite rule to say multiple bitcast can be cancelled, and when we add it the hack would fail

**Comment by chenyuxyz** [comment]
mostly fixed after #7507 , LLVM still fails because it might reorder compute
